---
title: "TIDAL CREEKS DASHBOARD"
output: 
  flexdashboard::flex_dashboard:
     logo: www/tarponlogo.png
runtime: shiny
css: styles.css
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = F, message = F, warning = F)

library(flexdashboard)
library(tidyverse)
library(tbeptools)
library(mapedit)
library(leaflet.extras)
library(sf)
library(reactable)
library(shinydashboard)

# # style file
# styles <- readLines('https://raw.githubusercontent.com/tbep-tech/css-styling/master/styles.css')
# writeLines(styles, 'styles.css')

data(tidres)
data(tidalcreeks)

source('R/funcs.R')

downloadButtonRmd <- function (outputId, label = "Download", class = NULL, ...)  {
  tags$a(id = outputId, class = paste("btn btn-default shiny-download-link", 
                                      class), href = "", target = "_blank", download = NA, 
         icon("download"), label, ...)
}

```

```{r reactives}
# overview map
allmap <- reactive({
  
  out <- show_tdlcrk(tidres)
  
  return(out)
  
})

# reactive edits module for map selection
edits <- reactive({
  
  # input
  allmap <- allmap()
  
  # this modifies available options in map selection toolber
  tomap <- allmap %>% 
    addDrawToolbar(
      polylineOptions = FALSE,
      circleOptions = FALSE,
      circleMarkerOptions = FALSE,
      markerOptions = FALSE,
      editOptions = editToolbarOptions()#,
      # singleFeature = TRUE
    )
  
  out <- callModule(editMod, 'editor', tomap)
  
  return(out)
  
})

# selection from map as sf object, same crs as biodat
mapsel <- reactive({

  # input
  edits <- edits()()
  
  # requires edits to continue  
  req(!is.null(edits$finished))

  # get selection
  out <- edits$finished %>% 
    st_transform(crs = st_crs(tidalcreeks)) %>% 
    st_intersection(tidalcreeks, .) %>% 
    st_set_geometry(NULL) %>% 
    left_join(tidres, by = c('id', 'wbid', 'JEI', 'class')) %>% 
    mutate(`Length (km)` = round(Creek_Length_m / 1000, 2)) %>% 
    select(wbid, JEI, `Length (km)`, target, caution, action, threshold, score)
  
  req(nrow(out) > 0)
  
  return(out)

})

# reactable output from map selection
maptab <- reactive({
  
  # requires edits to continue  
  validate(
    need(!is.null(edits()()$finished), 'Make selection from map')
  )
  
  # inputs
  mapsel <- mapsel()
  
  # format
  out <- reactable(mapsel, 
                   columns = list(
                         score = colDef(
                           style = function(value){
                             list(background = colfun(value))
                           }), 
                         `Length (km)` = colDef(
                            aggregate = 'sum', 
                            format = colFormat(digits = 2),
                            cell = function(value) {
                              
                              width <- paste0(value / max(mapsel$`Length (km)`) * 100, "%")
                              value <- format(value, width = 9, justify = "right")

                              bar <- div(
                                class = "bar-chart",
                                style = list(marginRight = "6px"),
                                div(class = "bar", style = list(width = width, backgroundColor = "#958984"))
                              )
                              div(class = "bar-cell", span(class = "number", value), bar)
                            }
                         ), 
                         # wbid = colDef(
                         #   aggregate = 'count'
                         # ), 
                         # JEI = colDef(
                         #   aggregate = 'count'
                         # ),
                         target = colDef(
                           aggregate = 'sum'
                         ), 
                         caution = colDef(
                           aggregate = 'sum'
                         ),  
                         action = colDef(
                           aggregate = 'sum'
                         ),  
                         threshold = colDef(
                           aggregate = 'sum'
                         )
                         
                    ), 
                   groupBy = 'score',
                   filterable = T, pageSizeOptions = c(10, 20, nrow(mapsel)), defaultPageSize = 10,
                   showPageSizeOptions = T, compact = T
  )
  
  return(out)
  
})

# no data gauge
nodtscr <- reactive({
  
  # input
  mapsel <- mapsel()
  sumsel <- input$sumsel
  typsel <- input$typsel
  
  # get gauge
  out <- sumfun(mapsel, sumsel, typsel, 'No Data')
  
  return(out)
  
})

# green gauge
grenscr <- reactive({
  
  # input
  mapsel <- mapsel()
  sumsel <- input$sumsel
  typsel <- input$typsel
  
  # get gauge
  out <- sumfun(mapsel, sumsel, typsel, 'Green')
  
  return(out)

})

# yellow gauge
yellscr <- reactive({
    
  # input
  mapsel <- mapsel()
  sumsel <- input$sumsel
  typsel <- input$typsel
  
  # get gauge
  out <- sumfun(mapsel, sumsel, typsel, 'Yellow')
  
  return(out)
  
})

# orange gauge
orngscr <- reactive({
    
  # input
  mapsel <- mapsel()
  sumsel <- input$sumsel
  typsel <- input$typsel
  
  # get gauge
  out <- sumfun(mapsel, sumsel, typsel, 'Orange')
  
  return(out)
  
})

# reds gauge
redsscr <- reactive({
  
  # input
  mapsel <- mapsel()
  sumsel <- input$sumsel
  typsel <- input$typsel
  
  # get gauge
  out <- sumfun(mapsel, sumsel, typsel, 'Red')
  
  return(out)
  
})

# summary text
sumtxt <- reactive({
  
  mapsel <- mapsel()
  sumsel <- input$sumsel
  typsel <- input$typsel
  
  req(typsel == 'sum')
  
  if(sumsel == 'by count')
    tot <- nrow(mapsel) %>% 
    paste('streams')
  
  if(sumsel == 'by creek length')
    tot <- sum(mapsel$`Length (km)`) %>% 
      round(1) %>% 
      paste('km')
    
  out <- paste('Total in selection:', tot)
  
  return(out)
  
})

# table on download tab
dwntab <- reactive({
  
  # requires edits to continue  
  validate(
    need(!is.null(edits()()$finished), 'Make selection from map')
  )
  
  # inputs
  mapsel <- mapsel()
  
  # format
  out <- reactable(mapsel, 
                   columns = list(
                         score = colDef(
                           style = function(value){
                             list(background = colfun(value))
                           })
                    ), 
                    filterable = T, pageSizeOptions = c(10, 20, nrow(mapsel)), defaultPageSize = 10,
                    showPageSizeOptions = T, compact = T
  )
  
  return(out)
  
})
```

```{r downloadhandlers}

# data for observed species
output$dldwndat <- downloadHandler(
  filename = function(){'tidalcreek_sel.csv'},
  content = function(file){
    todl <- mapsel() 
    write.csv(todl, file, quote = T, row.names = F)
  }
)
```

SUMMARY ASSESSMENTS
===========================================================

Column {.tabset .tabset-fade data-width=650}
-----------------------------------------------------------------------

### MAP SELECTION

```{r allmap}
output$nodtscr <- renderGauge(nodtscr())
output$grenscr <- renderGauge(grenscr())
output$yellscr <- renderGauge(yellscr())
output$orngscr <- renderGauge(orngscr())
output$redsscr <- renderGauge(redsscr())

fillRow(
  flex = c(0.5, 0.02,  1),
  editModUI('editor', height = 500),
  renderText(NULL), # spacer
  fillCol(
    flex = c(1, NA, 0.25),
    renderReactable(maptab()),
    inputPanel(
          selectInput('sumsel', 'Select summary category:', choices = c('by count', 'by creek length')), 
          selectInput('typsel', 'Select summary type:', choices = c('%', 'sum')), 
          renderText(sumtxt())
        ),
    fillRow(
      # column(12, 
      # shinydashboard::box(gaugeOutput('nodtscr'), title = HTML('<h5>No Data</h5>'), width = 2),
      # shinydashboard::box(gaugeOutput('grenscr'), title = HTML('<h5>Green</h5>'), width = 2),
      # shinydashboard::box(gaugeOutput('yellscr'), title = HTML('<h5>Yellow</h5>'), width = 2),
      # shinydashboard::box(gaugeOutput('orngscr'), title = HTML('<h5>Orange</h5>'), width = 2),
      # shinydashboard::box(gaugeOutput('redsscr'), title = HTML('<h5>Red</h5>'), width = 2)
      # )
      gaugeOutput('nodtscr'),
      gaugeOutput('grenscr'),
      gaugeOutput('yellscr'),
      gaugeOutput('orngscr'),
      gaugeOutput('redsscr')
    )
  )
)
```

### DOWNLOAD

```{r}
fillCol(
  flex = c(NA, 1),
  inputPanel(
    downloadButtonRmd('dldwntab', 'Download table')
  ),
  renderReactable(dwntab())
)
```



